spring:
  application:
    name: event-booking-backend
  datasource:
    url: jdbc:mysql://localhost:3307/demo_ebs_db
    username: root
    password: demopassword
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        web: debug
        security: debug