spring:
  application:
    name: event-booking-backend
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db
    username: root
    password: Password
  flyway:
    enabled: true
    locations: classpath:db/migration
