spring:
  application:
    name: event-booking-backend
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: Password
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: ALWAYS

#logging:
#  level:
#    org:
#      springframework:
#        web: debug
#        security: debug